# Generated by Django 2.1.7 on 2019-03-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20190301_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermanage',
            name='e_time',
            field=models.DateField(blank=True, null=True, verbose_name='完成日期'),
        ),
    ]
